name: Continuous Integrtion and Deployment  # any custom name

on:
 push:
  branches:
  - master  # can be customized

env:
  DOTNET_VERSION: '6.0.x'  # shall correspond to project runtime spesified
  AZURE_WEBAPP_NAME: CiCdWebApi00  # Azure Web App name (not servise plan)
  
jobs:
 build:
  runs-on: ubuntu-latest  # linux vm
  steps:  # here matrix of steps/environments can be applied 
  - name: Check out code  # any custom name
    uses: actions/checkout@v4  # get from action use description on website
  
  - name: Setup .Net 6  # custom name
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: ${{ env.DOTNET_VERSION }}  

  - name: Restore dependencies
    run: dotnet restore  # run shell/bash command

  - name: Build app
    run: dotnet build -c Release --no-restore  # run in Release (vs Debug), no need to restore (done above)

  - name: Run automated tests
    run: dotnet test -c Release --no-build  # built on previous step, can skip

  - name: Publish app
    run: dotnet publish -c Release -o ./out  # specify output directory "./out" 

  - name: Deploy to Azure Web Apps
    uses: azure/webapps-deploy@v3  # check current version
    with:
     app-name: ${{ env.AZURE_WEBAPP_NAME }}  
     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SECRET }}  # Github/Secrets/Actions
     package: ./out  # corresponds to output of Publish step